### ISSUE TITLE
Wifi ArtNet Timing

### ISSUE THREAD

**Issue by BasssT** [rstephan/ArtnetWifi#12]
Thank you very much for sharing your code. I can receive ArtNet data I generate with MadMapper. Unfortunately, I get some stuttering. The ArtNet packages are generated at 44 fps. Using Wireshark, I can see these packages at the ethernet port at approximately every 0,02 s. However, my router "groups" the packages and transmits e.g. ten with 0,0002 s temporal spacing. Afterwards there is a small break and so on. Almost all packets are received, but with a wrong timing. Because this is the case for both of the available routers (FritzBox and TimeCapsule) I was wondering if someone else had run into the same issue. Maybe there is a way to force the wifi router to preserve the ArtNet timing?

**Comment by rstephan** [comment]
What can I say?
WiFi uses a shared medium. If you router has to wait for the channel to be clear, then there will be a gap.
ArtNet was not design to be used in a wireless environment. Using an ESP is some kind of "out of spec". It is nice, no wire, but it has cons on the other side. 
If you need predictable real time then use DMX.
Sorry.
