### ISSUE TITLE
Multiple Receivers, Monitoring

### ISSUE THREAD

**Issue by Georgeeden** [rstephan/ArtnetWifi#22]
I am using the ArtNetWifiTransmit example which is working really well with 1 client but in the transmit example you set the ip for the destination and if I have multiple esp8266 receiving then how do I allow them all to receive it, also does the transmitter work with any monitoring apps as so far I haven’t found one that works (I am looking at eventually making a esp8266 that runs a HTML dashboard (not running from the transmitter because I don’t want to overload it.))

**Comment by rstephan** [comment]
You have to use the broadcast address.
If your clients are: 2.0.0.1, 2.0.0.2, 2.0.0.3, ... and if it is a 255.0.0.0 network the broadcast address will be 2.255.255.255
For a 192.168.0.1/24 network it will be 192.168.0.255 and so on.

Monitoring apps or even transmitter apps depend on the feature "OpPoll". It is a discovery for the network to find transmitters or receivers. This feature is not implemented is ArtnetWifi.
Take a look at my other project https://github.com/rstephan/ArtnetnodeWifi
