### ISSUE TITLE
Changing the type of artDmxCallback

### ISSUE THREAD

**Issue by em-esz** [rstephan/ArtnetWifi#23]
Hi,
Have you considered changing the type of artDmxCallback from raw function pointer to 
`std::function <void (uint16_t, uint16_t, uint8_t, uint8_t*)>`?

This would allow more flexibility for the callbacks (e.g. member functions, lambdas). Should be backward compatible as function pointers are automatically converted to std::function. 

I did a quick test and seems to work properly.

**Comment by rstephan** [comment]
Why not. I will consider it for my next update.
As long as I can maintain the compatibility with previous versions of the code.

**Comment by rstephan** [comment]
Something like this? Take a look at my `ArtnetWifiDebug2` example.
You can use either `setArtDmxCallback()` or `setArtDmxFunc()`.
