### ISSUE TITLE
Different artnet sub nets

### ISSUE THREAD

**Issue by rebeccagodfrey** [rstephan/ArtnetWifi#24]
How might I go about setting a different artnet subnet. Im building a large led matrix which will need16 universes but i still need a couple for my regular dmx lighting?
Thanks

**Comment by rstephan** [comment]
I am not an expert for building large scale lighting setups. But take a look at 
https://en.wikipedia.org/wiki/Art-Net and
https://artisticlicence.com/WebSiteMaster/User%20Guides/art-net.pdf
The network is based of the IP-protocol, so everything applies here as well. Use more nodes to reach more lights.
By the way, the universe field has a size of 15 bit, so up to 32768 universes per node are possible.
Hope this helps.
