### ISSUE TITLE
Add stop() function

### ISSUE THREAD

**Issue by benkuper** [rstephan/ArtnetWifi#55]
Hello,
thank you for this lib !
It would be great to be able to have a stop() function that stops the udp server to reduce power consumption when we want to disable artnet reception, in my case it's esp32's on battery and before the show we keep them connected but at minimum power, so disabling the UDP server would save some juce :)

**Comment by rstephan** [comment]
Hi,
I have added a `stop()` function. This only closes the inner UDP client.
To save energy, you have to disable WiFi for example or put the controller into sleep by yourself.
Stephan

**Comment by benkuper** [comment]
thanks !
