### ISSUE TITLE
Artnet Wifi connection lagging 

### ISSUE THREAD

**Issue by Shotario** [rstephan/ArtnetWifi#58]
Hello, I'm using esp32 wroom to light WS2812 strips from Resolume. Dev board has blue led, which indicates internet connection. When it's steady, lights are corresponding to signal. As soon as it's start blinking, led goes wrong, lagging. Even very close to router, notebook plugged to ethernet. I'm using single universe.  Connection isn't steady. Any suggestions?

**Comment by rstephan** [comment]
How much LEDs are connected? Do you have a big enough power supply. The required current can add up quickly with 100 or more LEDs.

**Comment by Shotario** [comment]
I was testing with a small amount, around 30 leds per strip. Ended up using
wled artnet and works flawless. I have no idea what caused signal lagging
and connection issues.
