### ISSUE TITLE
artnetwifi

### ISSUE THREAD

**Issue by mzhajjar** [rstephan/ArtnetWifi#7]
Hi

I have one project i need to use the art net WiFi for it, i have use the ESP-6288-12 with this http://www.ulrichradig.de/home/index.php/dmx/wlan-art-net-node

the project consist of 50 DMX Led Strip, each strip connect to 1 art net WiFi and using Madrix software to control them

when i connect 1 strip universe to the WiFi router it work fine and it still work fine till i connect the 10 universe

after that there is problem in synchronizing 

watch these videos 

https://www.youtube.com/watch?v=CZTpHP-Du6U
https://www.youtube.com/watch?v=K4GPopkt9f0
https://www.youtube.com/watch?v=eHDBiMwNT1A

i try many routers all are the same is there any solution you know about this
Zaki

**Comment by rstephan** [comment]
First of all, there are reasons for DMX in a cable and Art-Net on ethernet (also in a cable). Using Art-Net over WiFi is possible but sould be used only for small installations and not so timing critical animations. The upper limits of the ESP8266 are not known from my perspectiv

It is hard to say, with just a video, what is going "wrong" on your side. 
* Your problem could be somthing simple as a power supply problem. Do the universes all have a seperate power supply?
* Are the "nodes" very close to each other? So WiFi interferences are most likely. Event if you think they receive data only, that is not true, they have to responde to WiFi packets in your network.
* If you can, use less "nodes", my library can adress different universes in one devices.
* Is your computer and the software able to generate that much data in the right order?
* Can you test the Madrix software with other hardware?
* Use a tool like [Wireshark](https://www.wireshark.org/#download) to analyze the WiFi packets.

And finaly, many have tried to get an answer to "How many WS8212b can i connect to an ESP?" from me. I don't know. Build it and try it. That is all i can say. For your setup, it looks like 9 universes.

Are you using my library on this Ulrich Radig board? Just curiosity.
